<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BJGLPR-NMX0012.local" ignored="0" name="Default test" tests="3" failures="1" timestamp="13 三月 2019 03:28:37 GMT" time="10.915" errors="0">
  <testcase name="loginPageTitleTest" time="0.016" classname="com.crm.qa.testcaases.LoginPageTest"/>
  <testcase name="loginPageImageTest" time="0.038" classname="com.crm.qa.testcaases.LoginPageTest"/>
  <testcase name="loginTest" time="0.426" classname="com.crm.qa.testcaases.LoginPageTest">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	Default constructor cannot handle exception type IOException thrown by implicit super constructor. Must define an explicit constructor
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Default constructor cannot handle exception type IOException thrown by implicit super constructor. Must define an explicit constructor

at com.crm.qa.pages.HomePage.<init>(HomePage.java:5)
at com.crm.qa.pages.LoginPage.login(LoginPage.java:46)
at com.crm.qa.testcaases.LoginPageTest.loginTest(LoginPageTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Default test -->
